@startuml TrafficLight

' //////////////////////// STATE ORGANIZATION ///////////////////////
' Note: StateSmith treats state names and events as case insensitive.
' More info: https://github.com/StateSmith/StateSmith/wiki/PlantUML

state TrafficLightRed
state TrafficLightRedYellow
state TrafficLightGreen
state TrafficLightYellow


' ///////////////////////// STATE HANDLERS /////////////////////////
' Syntax: https://github.com/StateSmith/StateSmith/wiki/Behaviors

[*] --> TrafficLightRed : / initRedLight(); initYellowLight(); initGreenLight();

' TrafficLightRed
TrafficLightRed: enter / turnOnRedLight(); time = 0;
TrafficLightRed: exit  / turnOffRedLight();
TrafficLightRed: tick / time++;
TrafficLightRed --> TrafficLightRedYellow : requestGreen

' TrafficLightRedYellow
TrafficLightRedYellow: enter / turnOnRedLight(); turnOnYellowLight(); time = 0;
TrafficLightRedYellow: exit / turnOffRedLight(); turnOffYellowLight();
TrafficLightRedYellow: tick / time++;
TrafficLightRedYellow --> TrafficLightGreen : tick [time > 2000]

' TrafficLightGreen
TrafficLightGreen: enter / turnOnGreenLight(); time = 0;
TrafficLightGreen: exit  / turnOffGreenLight();
TrafficLightGreen: tick / time++;
TrafficLightGreen --> TrafficLightYellow : tick [time > 5000]

' TrafficLightYellow
TrafficLightYellow: enter / turnOnYellowLight(); time = 0;
TrafficLightYellow: exit  / turnOffYellowLight();
TrafficLightYellow: tick / time++;
TrafficLightYellow --> TrafficLightRed : tick [time > 3000]


' //////////////////////// StateSmith config ////////////////////////
' The below special comment block sets the StateSmith configuration.
' More info: https://github.com/StateSmith/StateSmith/issues/335

/'! $CONFIG : toml

[RenderConfig]
FileTop = """
    """
AutoExpandedVars = """
    uint16_t time;
    """

[RenderConfig.C]
CFileExtension = ".cpp"
HFileExtension = ".hpp"
HFileIncludes = """
    #include <stdint.h> // for time var
    """
CFileIncludes = """
    #include "driver.hpp"
    """

[SmRunnerSettings]
transpilerId = "C99"
'/
@enduml