@startuml TrafficLight

' //////////////////////// STATE ORGANIZATION ///////////////////////
' Note: StateSmith treats state names and events as case insensitive.
' More info: https://github.com/StateSmith/StateSmith/wiki/PlantUML

state TrafficLightRed
state TrafficLightRedYellow
state TrafficLightGreen
state TrafficLightYellow

state NightMode {
    state BlinkOn
    state BlinkOff

    [*] --> BlinkOff

    ' BlinkOff
    BlinkOff: enter / time = 0;
    BlinkOff: tick / time++;
    BlinkOff --> BlinkOn : tick [time > 1000]

    ' BlinkOn
    BlinkOn: enter / turnOnYellowLight(); time = 0;
    BlinkOn: exit / turnOffYellowLight();
    BlinkOn: tick / time++;
    BlinkOn --> BlinkOff : tick [time > 1000]
}


' ///////////////////////// STATE HANDLERS /////////////////////////
' Syntax: https://github.com/StateSmith/StateSmith/wiki/Behaviors

[*] --> TrafficLightRed : / initRedLight(); initYellowLight(); initGreenLight();

' TrafficLightRed
TrafficLightRed: enter / turnOnRedLight(); time = 0;
TrafficLightRed: exit  / turnOffRedLight();
TrafficLightRed: tick / time++;
TrafficLightRed --> TrafficLightRedYellow : requestGreen
TrafficLightRed --> NightMode : tick [brightness < threshold]

' TrafficLightRedYellow
TrafficLightRedYellow: enter / turnOnRedLight(); turnOnYellowLight(); time = 0;
TrafficLightRedYellow: exit / turnOffRedLight(); turnOffYellowLight();
TrafficLightRedYellow: tick / time++;
TrafficLightRedYellow --> TrafficLightGreen : tick [time > 2000]

' TrafficLightGreen
TrafficLightGreen: enter / turnOnGreenLight(); time = 0;
TrafficLightGreen: exit  / turnOffGreenLight();
TrafficLightGreen: tick / time++;
TrafficLightGreen --> TrafficLightYellow : tick [time > greenTime]

' TrafficLightYellow
TrafficLightYellow: enter / turnOnYellowLight(); time = 0;
TrafficLightYellow: exit  / turnOffYellowLight();
TrafficLightYellow: tick / time++;
TrafficLightYellow --> TrafficLightRed : tick [time > 3000]

' NightMode
NightMode --> TrafficLightRed : tick [brightness > threshold]


' //////////////////////// StateSmith config ////////////////////////
' The below special comment block sets the StateSmith configuration.
' More info: https://github.com/StateSmith/StateSmith/issues/335

/'! $CONFIG : toml

[RenderConfig]
FileTop = """
    """
AutoExpandedVars = """
    uint16_t time;
    uint16_t greenTime;
    uint16_t brightness;
    uint16_t threshold;
    """

[RenderConfig.C]
CFileExtension = ".cpp"
HFileExtension = ".hpp"
HFileIncludes = """
    #include <stdint.h> // for time var
    """
CFileIncludes = """
    #include "driver.hpp"
    """

[SmRunnerSettings]
transpilerId = "C99"
'/
@enduml