@startuml TrafficLight

' //////////////////////// STATE ORGANIZATION ///////////////////////
' Note: StateSmith treats state names and events as case insensitive.
' More info: https://github.com/StateSmith/StateSmith/wiki/PlantUML

state TrafficLightRed
state TrafficLightRedYellow
state TrafficLightGreen
state TrafficLightYellow

state NightMode {
    state BlinkOn
    state BlinkOff

    [*] --> BlinkOff

    ' BlinkOff
    BlinkOff: enter / time = 0;
    BlinkOff: tick / time++;
    BlinkOff --> BlinkOn : tick [time > 1000]
    BlinkOff --> TrafficLightRed : tick [brightness > threshold + 100]

    ' BlinkOn
    BlinkOn: enter / turnOnLight(pinYellow); time = 0;
    BlinkOn: exit / turnOffLight(pinYellow);
    BlinkOn: tick / time++;
    BlinkOn --> BlinkOff : tick [time > 1000]
    BlinkOn --> TrafficLightRed : tick [brightness > threshold + 100]
}


' ///////////////////////// STATE HANDLERS /////////////////////////
' Syntax: https://github.com/StateSmith/StateSmith/wiki/Behaviors

[*] --> TrafficLightRed : / initLight(pinRed); initLight(pinYellow); initLight(pinGreen);

' TrafficLightRed
TrafficLightRed: enter / turnOnLight(pinRed); time = 0;
TrafficLightRed: exit  / turnOffLight(pinRed);
TrafficLightRed: tick / time++;
TrafficLightRed --> TrafficLightRedYellow : requestGreen
TrafficLightRed --> NightMode : tick [brightness < threshold - 100]

' TrafficLightRedYellow
TrafficLightRedYellow: enter / turnOnLight(pinRed); turnOnLight(pinYellow); time = 0;
TrafficLightRedYellow: exit / turnOffLight(pinRed); turnOffLight(pinYellow);
TrafficLightRedYellow: tick / time++;
TrafficLightRedYellow --> TrafficLightGreen : tick [time > 2000]

' TrafficLightGreen
TrafficLightGreen: enter / turnOnLight(pinGreen); time = 0;
TrafficLightGreen: exit  / turnOffLight(pinGreen);
TrafficLightGreen: tick / time++;
TrafficLightGreen --> TrafficLightYellow : tick [time > greenTime]

' TrafficLightYellow
TrafficLightYellow: enter / turnOnLight(pinYellow); time = 0;
TrafficLightYellow: exit  / turnOffLight(pinYellow);
TrafficLightYellow: tick / time++;
TrafficLightYellow --> TrafficLightRed : tick [time > 3000]



' //////////////////////// StateSmith config ////////////////////////
' The below special comment block sets the StateSmith configuration.
' More info: https://github.com/StateSmith/StateSmith/issues/335

/'! $CONFIG : toml

[RenderConfig]
FileTop = """
    """
AutoExpandedVars = """
    uint8_t pinRed;
    uint8_t pinYellow;
    uint8_t pinGreen;

    uint16_t time;
    uint16_t greenTime;
    uint16_t brightness;
    uint16_t threshold;
    """

[RenderConfig.C]
CFileExtension = ".cpp"
HFileExtension = ".hpp"
HFileIncludes = """
    #include <stdint.h> // for time var
    """
CFileIncludes = """
    #include "driver.hpp"
    """

[SmRunnerSettings]
transpilerId = "C99"
'/
@enduml