// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

    
#pragma once  // You can also specify normal include guard. See https://github.com/StateSmith/StateSmith/blob/main/docs/settings.md
#include <stdint.h>
#include <stdint.h> // for time var


typedef enum TrafficLight_EventId
{
    TrafficLight_EventId_REQUESTGREEN = 0,
    TrafficLight_EventId_TICK = 1
} TrafficLight_EventId;

enum
{
    TrafficLight_EventIdCount = 2
};

typedef enum TrafficLight_StateId
{
    TrafficLight_StateId_ROOT = 0,
    TrafficLight_StateId_NIGHTMODE = 1,
    TrafficLight_StateId_BLINKOFF = 2,
    TrafficLight_StateId_BLINKON = 3,
    TrafficLight_StateId_TRAFFICLIGHTGREEN = 4,
    TrafficLight_StateId_TRAFFICLIGHTRED = 5,
    TrafficLight_StateId_TRAFFICLIGHTREDYELLOW = 6,
    TrafficLight_StateId_TRAFFICLIGHTYELLOW = 7
} TrafficLight_StateId;

enum
{
    TrafficLight_StateIdCount = 8
};


// Generated state machine
// forward declaration
typedef struct TrafficLight TrafficLight;

// State machine variables. Can be used for inputs, outputs, user variables...
typedef struct TrafficLight_Vars
{
    uint16_t time;
    uint16_t greenTime;
    uint16_t brightness;
    uint16_t threshold;
} TrafficLight_Vars;


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void TrafficLight_ctor(TrafficLight* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void TrafficLight_start(TrafficLight* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void TrafficLight_dispatch_event(TrafficLight* sm, TrafficLight_EventId event_id);

// Thread safe.
char const * TrafficLight_state_id_to_string(TrafficLight_StateId id);

// Thread safe.
char const * TrafficLight_event_id_to_string(TrafficLight_EventId id);

// Generated state machine
struct TrafficLight
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    TrafficLight_StateId state_id;
    
    // Variables. Can be used for inputs, outputs, user variables...
    TrafficLight_Vars vars;
};

