// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

    
#include "TrafficLight.hpp"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset
#include "driver.hpp"


// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(TrafficLight* sm, TrafficLight_StateId desired_state);

static void ROOT_enter(TrafficLight* sm);

static void NIGHTMODE_enter(TrafficLight* sm);

static void NIGHTMODE_exit(TrafficLight* sm);

static void BLINKOFF_enter(TrafficLight* sm);

static void BLINKOFF_exit(TrafficLight* sm);

static void BLINKOFF_tick(TrafficLight* sm);

static void BLINKON_enter(TrafficLight* sm);

static void BLINKON_exit(TrafficLight* sm);

static void BLINKON_tick(TrafficLight* sm);

static void TRAFFICLIGHTGREEN_enter(TrafficLight* sm);

static void TRAFFICLIGHTGREEN_exit(TrafficLight* sm);

static void TRAFFICLIGHTGREEN_tick(TrafficLight* sm);

static void TRAFFICLIGHTRED_enter(TrafficLight* sm);

static void TRAFFICLIGHTRED_exit(TrafficLight* sm);

static void TRAFFICLIGHTRED_requestgreen(TrafficLight* sm);

static void TRAFFICLIGHTRED_tick(TrafficLight* sm);

static void TRAFFICLIGHTREDYELLOW_enter(TrafficLight* sm);

static void TRAFFICLIGHTREDYELLOW_exit(TrafficLight* sm);

static void TRAFFICLIGHTREDYELLOW_tick(TrafficLight* sm);

static void TRAFFICLIGHTYELLOW_enter(TrafficLight* sm);

static void TRAFFICLIGHTYELLOW_exit(TrafficLight* sm);

static void TRAFFICLIGHTYELLOW_tick(TrafficLight* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void TrafficLight_ctor(TrafficLight* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void TrafficLight_start(TrafficLight* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: / { initLight(pinRed); initLight(pinYellow); initLight(pinGreen); } TransitionTo(TrafficLightRed)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: `initLight(pinRed); initLight(pinYellow); initLight(pinGreen);`.
            initLight(sm->vars.pinRed); initLight(sm->vars.pinYellow); initLight(sm->vars.pinGreen);
            
            // Step 3: Enter/move towards transition target `TrafficLightRed`.
            TRAFFICLIGHTRED_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void TrafficLight_dispatch_event(TrafficLight* sm, TrafficLight_EventId event_id)
{
    switch (sm->state_id)
    {
        // STATE: TrafficLight
        case TrafficLight_StateId_ROOT:
            // No events handled by this state (or its ancestors).
            break;
        
        // STATE: NightMode
        case TrafficLight_StateId_NIGHTMODE:
            // No events handled by this state (or its ancestors).
            break;
        
        // STATE: BlinkOff
        case TrafficLight_StateId_BLINKOFF:
            switch (event_id)
            {
                case TrafficLight_EventId_TICK: BLINKOFF_tick(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: BlinkOn
        case TrafficLight_StateId_BLINKON:
            switch (event_id)
            {
                case TrafficLight_EventId_TICK: BLINKON_tick(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: TrafficLightGreen
        case TrafficLight_StateId_TRAFFICLIGHTGREEN:
            switch (event_id)
            {
                case TrafficLight_EventId_TICK: TRAFFICLIGHTGREEN_tick(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: TrafficLightRed
        case TrafficLight_StateId_TRAFFICLIGHTRED:
            switch (event_id)
            {
                case TrafficLight_EventId_TICK: TRAFFICLIGHTRED_tick(sm); break;
                case TrafficLight_EventId_REQUESTGREEN: TRAFFICLIGHTRED_requestgreen(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: TrafficLightRedYellow
        case TrafficLight_StateId_TRAFFICLIGHTREDYELLOW:
            switch (event_id)
            {
                case TrafficLight_EventId_TICK: TRAFFICLIGHTREDYELLOW_tick(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: TrafficLightYellow
        case TrafficLight_StateId_TRAFFICLIGHTYELLOW:
            switch (event_id)
            {
                case TrafficLight_EventId_TICK: TRAFFICLIGHTYELLOW_tick(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(TrafficLight* sm, TrafficLight_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case TrafficLight_StateId_NIGHTMODE: NIGHTMODE_exit(sm); break;
            
            case TrafficLight_StateId_BLINKOFF: BLINKOFF_exit(sm); break;
            
            case TrafficLight_StateId_BLINKON: BLINKON_exit(sm); break;
            
            case TrafficLight_StateId_TRAFFICLIGHTGREEN: TRAFFICLIGHTGREEN_exit(sm); break;
            
            case TrafficLight_StateId_TRAFFICLIGHTRED: TRAFFICLIGHTRED_exit(sm); break;
            
            case TrafficLight_StateId_TRAFFICLIGHTREDYELLOW: TRAFFICLIGHTREDYELLOW_exit(sm); break;
            
            case TrafficLight_StateId_TRAFFICLIGHTYELLOW: TRAFFICLIGHTYELLOW_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(TrafficLight* sm)
{
    sm->state_id = TrafficLight_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state NIGHTMODE
////////////////////////////////////////////////////////////////////////////////

static void NIGHTMODE_enter(TrafficLight* sm)
{
    sm->state_id = TrafficLight_StateId_NIGHTMODE;
}

static void NIGHTMODE_exit(TrafficLight* sm)
{
    sm->state_id = TrafficLight_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state BLINKOFF
////////////////////////////////////////////////////////////////////////////////

static void BLINKOFF_enter(TrafficLight* sm)
{
    sm->state_id = TrafficLight_StateId_BLINKOFF;
    
    // BlinkOff behavior
    // uml: enter / { time = 0; }
    {
        // Step 1: execute action `time = 0;`
        sm->vars.time = 0;
    } // end of behavior for BlinkOff
}

static void BLINKOFF_exit(TrafficLight* sm)
{
    sm->state_id = TrafficLight_StateId_NIGHTMODE;
}

static void BLINKOFF_tick(TrafficLight* sm)
{
    // BlinkOff behavior
    // uml: tick / { time++; }
    {
        // Step 1: execute action `time++;`
        sm->vars.time++;
    } // end of behavior for BlinkOff
    
    // BlinkOff behavior
    // uml: tick [time > 1000] TransitionTo(BlinkOn)
    if (sm->vars.time > 1000)
    {
        // Step 1: Exit states until we reach `NightMode` state (Least Common Ancestor for transition).
        BLINKOFF_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `BlinkOn`.
        BLINKON_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for BlinkOff
    
    // BlinkOff behavior
    // uml: tick [brightness > threshold + 100] TransitionTo(TrafficLightRed)
    if (sm->vars.brightness > sm->vars.threshold + 100)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, TrafficLight_StateId_ROOT);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightRed`.
        TRAFFICLIGHTRED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for BlinkOff
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state BLINKON
////////////////////////////////////////////////////////////////////////////////

static void BLINKON_enter(TrafficLight* sm)
{
    sm->state_id = TrafficLight_StateId_BLINKON;
    
    // BlinkOn behavior
    // uml: enter / { turnOnYellowLight(); time = 0; }
    {
        // Step 1: execute action `turnOnYellowLight(); time = 0;`
        turnOnYellowLight(); sm->vars.time = 0;
    } // end of behavior for BlinkOn
}

static void BLINKON_exit(TrafficLight* sm)
{
    // BlinkOn behavior
    // uml: exit / { turnOffYellowLight(); }
    {
        // Step 1: execute action `turnOffYellowLight();`
        turnOffYellowLight();
    } // end of behavior for BlinkOn
    
    sm->state_id = TrafficLight_StateId_NIGHTMODE;
}

static void BLINKON_tick(TrafficLight* sm)
{
    // BlinkOn behavior
    // uml: tick / { time++; }
    {
        // Step 1: execute action `time++;`
        sm->vars.time++;
    } // end of behavior for BlinkOn
    
    // BlinkOn behavior
    // uml: tick [time > 1000] TransitionTo(BlinkOff)
    if (sm->vars.time > 1000)
    {
        // Step 1: Exit states until we reach `NightMode` state (Least Common Ancestor for transition).
        BLINKON_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `BlinkOff`.
        BLINKOFF_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for BlinkOn
    
    // BlinkOn behavior
    // uml: tick [brightness > threshold + 100] TransitionTo(TrafficLightRed)
    if (sm->vars.brightness > sm->vars.threshold + 100)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, TrafficLight_StateId_ROOT);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightRed`.
        TRAFFICLIGHTRED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for BlinkOn
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRAFFICLIGHTGREEN
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICLIGHTGREEN_enter(TrafficLight* sm)
{
    sm->state_id = TrafficLight_StateId_TRAFFICLIGHTGREEN;
    
    // TrafficLightGreen behavior
    // uml: enter / { turnOnLight(pinGreen); time = 0; }
    {
        // Step 1: execute action `turnOnLight(pinGreen); time = 0;`
        turnOnLight(sm->vars.pinGreen); sm->vars.time = 0;
    } // end of behavior for TrafficLightGreen
}

static void TRAFFICLIGHTGREEN_exit(TrafficLight* sm)
{
    // TrafficLightGreen behavior
    // uml: exit / { turnOffLight(pinGreen); }
    {
        // Step 1: execute action `turnOffLight(pinGreen);`
        turnOffLight(sm->vars.pinGreen);
    } // end of behavior for TrafficLightGreen
    
    sm->state_id = TrafficLight_StateId_ROOT;
}

static void TRAFFICLIGHTGREEN_tick(TrafficLight* sm)
{
    // TrafficLightGreen behavior
    // uml: tick / { time++; }
    {
        // Step 1: execute action `time++;`
        sm->vars.time++;
    } // end of behavior for TrafficLightGreen
    
    // TrafficLightGreen behavior
    // uml: tick [time > greenTime] TransitionTo(TrafficLightYellow)
    if (sm->vars.time > sm->vars.greenTime)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTGREEN_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightYellow`.
        TRAFFICLIGHTYELLOW_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightGreen
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRAFFICLIGHTRED
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICLIGHTRED_enter(TrafficLight* sm)
{
    sm->state_id = TrafficLight_StateId_TRAFFICLIGHTRED;
    
    // TrafficLightRed behavior
    // uml: enter / { turnOnLight(pinRed); time = 0; }
    {
        // Step 1: execute action `turnOnLight(pinRed); time = 0;`
        turnOnLight(sm->vars.pinRed); sm->vars.time = 0;
    } // end of behavior for TrafficLightRed
}

static void TRAFFICLIGHTRED_exit(TrafficLight* sm)
{
    // TrafficLightRed behavior
    // uml: exit / { turnOffLight(pinRed); }
    {
        // Step 1: execute action `turnOffLight(pinRed);`
        turnOffLight(sm->vars.pinRed);
    } // end of behavior for TrafficLightRed
    
    sm->state_id = TrafficLight_StateId_ROOT;
}

static void TRAFFICLIGHTRED_requestgreen(TrafficLight* sm)
{
    // TrafficLightRed behavior
    // uml: requestGreen TransitionTo(TrafficLightRedYellow)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTRED_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightRedYellow`.
        TRAFFICLIGHTREDYELLOW_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightRed
    
    // No ancestor handles this event.
}

static void TRAFFICLIGHTRED_tick(TrafficLight* sm)
{
    // TrafficLightRed behavior
    // uml: tick / { time++; }
    {
        // Step 1: execute action `time++;`
        sm->vars.time++;
    } // end of behavior for TrafficLightRed
    
    // TrafficLightRed behavior
    // uml: tick [brightness < threshold - 100] TransitionTo(NightMode)
    if (sm->vars.brightness < sm->vars.threshold - 100)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTRED_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `NightMode`.
        NIGHTMODE_enter(sm);
        
        // NightMode.<InitialState> behavior
        // uml: TransitionTo(BlinkOff)
        {
            // Step 1: Exit states until we reach `NightMode` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `BlinkOff`.
            BLINKOFF_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for NightMode.<InitialState>
    } // end of behavior for TrafficLightRed
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRAFFICLIGHTREDYELLOW
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICLIGHTREDYELLOW_enter(TrafficLight* sm)
{
    sm->state_id = TrafficLight_StateId_TRAFFICLIGHTREDYELLOW;
    
    // TrafficLightRedYellow behavior
    // uml: enter / { turnOnLight(pinRed); turnOnLight(pinYellow); time = 0; }
    {
        // Step 1: execute action `turnOnLight(pinRed); turnOnLight(pinYellow); time = 0;`
        turnOnLight(sm->vars.pinRed); turnOnLight(sm->vars.pinYellow); sm->vars.time = 0;
    } // end of behavior for TrafficLightRedYellow
}

static void TRAFFICLIGHTREDYELLOW_exit(TrafficLight* sm)
{
    // TrafficLightRedYellow behavior
    // uml: exit / { turnOffLight(pinRed); turnOffLight(pinYellow); }
    {
        // Step 1: execute action `turnOffLight(pinRed); turnOffLight(pinYellow);`
        turnOffLight(sm->vars.pinRed); turnOffLight(sm->vars.pinYellow);
    } // end of behavior for TrafficLightRedYellow
    
    sm->state_id = TrafficLight_StateId_ROOT;
}

static void TRAFFICLIGHTREDYELLOW_tick(TrafficLight* sm)
{
    // TrafficLightRedYellow behavior
    // uml: tick / { time++; }
    {
        // Step 1: execute action `time++;`
        sm->vars.time++;
    } // end of behavior for TrafficLightRedYellow
    
    // TrafficLightRedYellow behavior
    // uml: tick [time > 2000] TransitionTo(TrafficLightGreen)
    if (sm->vars.time > 2000)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTREDYELLOW_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightGreen`.
        TRAFFICLIGHTGREEN_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightRedYellow
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRAFFICLIGHTYELLOW
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICLIGHTYELLOW_enter(TrafficLight* sm)
{
    sm->state_id = TrafficLight_StateId_TRAFFICLIGHTYELLOW;
    
    // TrafficLightYellow behavior
    // uml: enter / { turnOnLight(pinYellow); time = 0; }
    {
        // Step 1: execute action `turnOnLight(pinYellow); time = 0;`
        turnOnLight(sm->vars.pinYellow); sm->vars.time = 0;
    } // end of behavior for TrafficLightYellow
}

static void TRAFFICLIGHTYELLOW_exit(TrafficLight* sm)
{
    // TrafficLightYellow behavior
    // uml: exit / { turnOffLight(pinYellow); }
    {
        // Step 1: execute action `turnOffLight(pinYellow);`
        turnOffLight(sm->vars.pinYellow);
    } // end of behavior for TrafficLightYellow
    
    sm->state_id = TrafficLight_StateId_ROOT;
}

static void TRAFFICLIGHTYELLOW_tick(TrafficLight* sm)
{
    // TrafficLightYellow behavior
    // uml: tick / { time++; }
    {
        // Step 1: execute action `time++;`
        sm->vars.time++;
    } // end of behavior for TrafficLightYellow
    
    // TrafficLightYellow behavior
    // uml: tick [time > 3000] TransitionTo(TrafficLightRed)
    if (sm->vars.time > 3000)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTYELLOW_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightRed`.
        TRAFFICLIGHTRED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightYellow
    
    // No ancestor handles this event.
}

// Thread safe.
char const * TrafficLight_state_id_to_string(TrafficLight_StateId id)
{
    switch (id)
    {
        case TrafficLight_StateId_ROOT: return "ROOT";
        case TrafficLight_StateId_NIGHTMODE: return "NIGHTMODE";
        case TrafficLight_StateId_BLINKOFF: return "BLINKOFF";
        case TrafficLight_StateId_BLINKON: return "BLINKON";
        case TrafficLight_StateId_TRAFFICLIGHTGREEN: return "TRAFFICLIGHTGREEN";
        case TrafficLight_StateId_TRAFFICLIGHTRED: return "TRAFFICLIGHTRED";
        case TrafficLight_StateId_TRAFFICLIGHTREDYELLOW: return "TRAFFICLIGHTREDYELLOW";
        case TrafficLight_StateId_TRAFFICLIGHTYELLOW: return "TRAFFICLIGHTYELLOW";
        default: return "?";
    }
}

// Thread safe.
char const * TrafficLight_event_id_to_string(TrafficLight_EventId id)
{
    switch (id)
    {
        case TrafficLight_EventId_REQUESTGREEN: return "REQUESTGREEN";
        case TrafficLight_EventId_TICK: return "TICK";
        default: return "?";
    }
}
